### ISSUE TITLE
unicode problem

### ISSUE THREAD

**Issue by xsuperbug** [sawzeeyy/Sanitiz3r#1]
[+] 60 URLs / Subdomains Sanitiz3d
[+] Now checking the individual subdomains
[-] Checking 3.tesla.com
	[+] Status: 200
	[+] Title: Electric Cars, Solar Panels & Clean Energy Storage | Tesla
[-] Checking auth.tesla.com
	[+] Status: 200
Traceback (most recent call last):
  File "sanitiz3r.py", line 316, in <module>
    if __name__ == '__main__': sanitiz3r()
  File "sanitiz3r.py", line 306, in sanitiz3r
    status = get_status(urls, 10, args)
  File "sanitiz3r.py", line 115, in get_status
    url_and_status = [get_url_status(url, time_out, args) for url in urls]
  File "sanitiz3r.py", line 141, in get_url_status
    if (arguments.verbose): print('\t{}[+] Title: {}{}'.format(Y, https_title, C))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 10: ordinal not in range(128)

**Comment by sawzeeyy** [comment]
Hi @xsuperbug, is this resolved on your end?

**Comment by sawzeeyy** [comment]
The issue has been addressed via https://github.com/sawzeeyy/Sanitiz3r/commit/95baf2312e0394ceb48b13246652b72e67014afa

Thanks for flagging the error and please do confirm this resolved on your end.

**Comment by sawzeeyy** [comment]
Issue Resolved!
