### ISSUE TITLE
Threads Switch

### ISSUE THREAD

**Issue by jaikishantulswani** [sawzeeyy/Sanitiz3r#2]
Is there any switch to set threads ?

**Comment by sawzeeyy** [comment]
Hi @jaikishantulswani threads is not yet included but will be soon.

**Comment by jaikishantulswani** [comment]
Hello @sawzeeyy 
Waiting for threads switch to be added.

**Comment by sawzeeyy** [comment]
Hi @jaikishantulswani,

Thanks again for the reminder. I'll work on this as soon as possible and notify you once it's included.

**Comment by sawzeeyy** [comment]
Hi @jaikishantulswani,

This seem to have taken a lot of time but I wanted to inform you that threads have been added, thanks.
